apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kuberenetes.io/component: talm
    app.kubernetes.io/name: talm-operator
    control-plane: controller-manager
  name: cluster-group-upgrades-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kuberenetes.io/component: talm
    app.kubernetes.io/name: talm-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
